# 发送短信token的有效期
SEND_SMS_CODE_TOKEN_EXPIRES = 300

# 修改密码的token有效期
SET_PASSWORD_TOKEN_EXPIRES = 300

# 邮箱验证的token有效期
EMAIL_VERIFY_TOKEN_EXPIRES = 24 * 60 * 60

# 用户最多保存地址数量限制
USER_ADDRESS_COUNTS_LIMIT = 10

USER_BROWSE_HISTORY_LIMIT = 5